apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql-config
data:
  init.sql: |
    CREATE TABLE usuarios (id SERIAL PRIMARY KEY, nombre VARCHAR(100) NOT NULL, email VARCHAR(100) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE tareas (id SERIAL PRIMARY KEY, usuario_id INTEGER REFERENCES usuarios(id), titulo VARCHAR(100) NOT NULL, descripcion TEXT, prioridad VARCHAR(50), categoria VARCHAR(50), estado VARCHAR(50) DEFAULT 'pendiente', fecha_limite DATE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
