# Usa una imagen de Node.js para construir la aplicación Angular
FROM node:18 as builder

# Crea y establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de configuración
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el código fuente
COPY . .

# Construye la aplicación para producción
RUN npm run build --prod

# Usa una imagen ligera de Nginx para servir la aplicación Angular
FROM nginx:alpine

# Copia los archivos de la build a la carpeta de Nginx
COPY --from=builder /app/dist/capi-task-app/browser /usr/share/nginx/html

# Exponer el puerto 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]