# Usa una imagen oficial de Node.js
FROM node:18

# Crea y establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de configuración
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el código fuente
COPY . .

# Exponer el puerto en el que corre tu aplicación
EXPOSE 3000

# Comando para iniciar el servidor
CMD ["npm", "start"]
